name: Koin docs update

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at 0:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-external-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete history for diff comparison

      - name: Checkout Koin repository
        uses: actions/checkout@v4
        with:
          repository: InsertKoinIO/koin
          path: koin-repo

      - name: Checkout Koin Annotations repository
        uses: actions/checkout@v4
        with:
          repository: InsertKoinIO/koin-annotations
          path: koin-annotations-repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @google/genai

      - name: Check last run timestamp for Koin
        id: last-run-koin
        run: |
          if [ -f ".github/last_check_koin.txt" ]; then
            echo "first_run=false" >> $GITHUB_OUTPUT
            echo "last_commit=$(cat .github/last_check_koin.txt)" >> $GITHUB_OUTPUT
          else
            echo "first_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Check last run timestamp for Koin-Annotations
        id: last-run-annotations
        run: |
          if [ -f ".github/last_check_koin_annotations.txt" ]; then
            echo "first_run=false" >> $GITHUB_OUTPUT
            echo "last_commit=$(cat .github/last_check_koin_annotations.txt)" >> $GITHUB_OUTPUT
          else
            echo "first_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Get current commit for Koin
        id: current-commit-koin
        run: |
          cd koin-repo
          echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get current commit for Koin-Annotations
        id: current-commit-annotations
        run: |
          cd koin-annotations-repo
          echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check if commits have changed
        id: check-commits
        run: |
          # Check if Koin repository's commit has changed
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            echo "koin_changed=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.last-run-koin.outputs.last_commit }}" != "${{ steps.current-commit-koin.outputs.current_commit }}" ]; then
            echo "koin_changed=true" >> $GITHUB_OUTPUT
          else
            echo "koin_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # Check if Koin-Annotations repository's commit has changed
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            echo "annotations_changed=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.last-run-annotations.outputs.last_commit }}" != "${{ steps.current-commit-annotations.outputs.current_commit }}" ]; then
            echo "annotations_changed=true" >> $GITHUB_OUTPUT
          else
            echo "annotations_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # Any repository has changed
          if [[ "${{ steps.check-commits.outputs.koin_changed }}" == "true" || "${{ steps.check-commits.outputs.annotations_changed }}" == "true" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi
          
          echo "Koin repository changed: ${{ steps.check-commits.outputs.koin_changed }}"
          echo "Koin-Annotations repository changed: ${{ steps.check-commits.outputs.annotations_changed }}"
          echo "Any repository changed: ${{ steps.check-commits.outputs.any_changed }}"

      - name: Get changed markdown files for Koin
        id: changed-files-koin
        if: steps.check-commits.outputs.koin_changed == 'true'
        uses: tj-actions/changed-files@v46.0.3
        with:
          path: koin-repo
          base_sha: ${{ steps.last-run-koin.outputs.last_commit }}
          files: |
            docs/**/*.md

      - name: Get changed markdown files for Koin-Annotations
        id: changed-files-annotations
        if: steps.check-commits.outputs.annotations_changed == 'true'
        uses: tj-actions/changed-files@v46.0.3
        with:
          path: koin-annotations-repo
          base_sha: ${{ steps.last-run-annotations.outputs.last_commit }}
          files: |
            docs/**/*.md

      - name: Get all markdown files for Koin (first run)
        id: all-files-koin
        if: steps.last-run-koin.outputs.first_run == 'true'
        run: |
          cd koin-repo
          ALL_FILES=$(find docs -name "*.md" | tr '\n' ' ' | sed 's/ $//')
          echo "all_changed_files=$ALL_FILES" >>  $GITHUB_OUTPUT

      - name: Get all markdown files for Koin-Annotations (first run)
        id: all-files-annotations
        if: steps.last-run-annotations.outputs.first_run == 'true'
        run: |
          cd koin-annotations-repo
          ALL_FILES=$(find docs -name "*.md" | tr '\n' ' ' | sed 's/ $//')
          echo "all_changed_files=$ALL_FILES" >>  $GITHUB_OUTPUT

      - name: Prepare files for translation
        id: prepare-translation
        run: |
          # Process Koin repository files
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            # First run - use all files
            echo "KOIN_CHANGED_FILES=${{ steps.all-files-koin.outputs.all_changed_files }}" >> $GITHUB_ENV
            echo "koin_any_changed=true" >> $GITHUB_OUTPUT
          else
            # Subsequent runs - use changed files
            echo "KOIN_CHANGED_FILES=${{ steps.changed-files-koin.outputs.all_changed_files }}" >> $GITHUB_ENV
          
            if [ -n "${{ steps.changed-files-koin.outputs.all_changed_files }}" ]; then
              echo "koin_any_changed=true" >> $GITHUB_OUTPUT
            else
              echo "koin_any_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          # Process Koin-Annotations repository files
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            # First run - use all files
            echo "ANNOTATIONS_CHANGED_FILES=${{ steps.all-files-annotations.outputs.all_changed_files }}" >> $GITHUB_ENV
            echo "annotations_any_changed=true" >> $GITHUB_OUTPUT
          else
            # Subsequent runs - use changed files
            echo "ANNOTATIONS_CHANGED_FILES=${{ steps.changed-files-annotations.outputs.all_changed_files }}" >> $GITHUB_ENV
          
            if [ -n "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]; then
              echo "annotations_any_changed=true" >> $GITHUB_OUTPUT
            else
              echo "annotations_any_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          # Any repository has changes
          if [[ "${{ steps.last-run-koin.outputs.first_run }}" == "true" || "${{ steps.last-run-annotations.outputs.first_run }}" == "true" || -n "${{ steps.changed-files-koin.outputs.all_changed_files }}" || -n "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # Save current commit SHA for future updates
          cd koin-repo
          echo "KOIN_CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
          cd ../koin-annotations-repo
          echo "ANNOTATIONS_CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Translate Koin docs
        if: steps.prepare-translation.outputs.koin_any_changed == 'true'
        env:
          BASE_DIR: ./koin
          START_PAGE: koin.md
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CHANGED_FILES: ${{ env.KOIN_CHANGED_FILES }}
          REPO_PATH: koin-repo
        run: node .github/workflows/translate.js

      - name: Translate Koin-Annotations docs
        if: steps.prepare-translation.outputs.annotations_any_changed == 'true'
        env:
          BASE_DIR: ./koin
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CHANGED_FILES: ${{ env.ANNOTATIONS_CHANGED_FILES }}
          REPO_PATH: koin-annotations-repo
        run: node .github/workflows/translate.js

      - name: Update last check timestamps
        if: success() && steps.prepare-translation.outputs.any_changed == 'true'
        run: |
          # Only update the last checked commit if all previous steps were successful
          echo "${{ env.KOIN_CURRENT_COMMIT }}" > .github/last_check_koin.txt
          echo "${{ env.ANNOTATIONS_CURRENT_COMMIT }}" > .github/last_check_koin_annotations.txt
          echo "Updated check record timestamps"

      - name: Commit and push changes
        if: steps.prepare-translation.outputs.any_changed == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          # Exclude files and directories that don't need to be committed
          git add . ':!package.json' ':!package-lock.json' ':!koin-repo' ':!koin-repo/**' ':!koin-annotations-repo' ':!koin-annotations-repo/**'
          git commit -m 'Add translated files and update check record'
          git push origin main

      - name: Create summary
        if: always()
        run: |
          echo "## Documentation Update Detection" >> $GITHUB_STEP_SUMMARY
          
          # Check if commit changed
          echo "### Commit Change Detection" >> $GITHUB_STEP_SUMMARY
          echo "- Koin repository: ${{ steps.check-commits.outputs.koin_changed }}" >> $GITHUB_STEP_SUMMARY
          echo "- Koin-Annotations repository: ${{ steps.check-commits.outputs.annotations_changed }}" >> $GITHUB_STEP_SUMMARY
          
          # Koin repository summary
          echo "### Koin Repository" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            echo "First run - processed all documentation files" >> $GITHUB_STEP_SUMMARY
            FILES="${{ steps.all-files-koin.outputs.all_changed_files }}"
            COUNT=$(echo "$FILES" | wc -w)
            echo "Processed $COUNT files in total" >> $GITHUB_STEP_SUMMARY
          else
            if [ -z "${{ steps.changed-files-koin.outputs.all_changed_files }}" ]; then
              echo "No document changes detected" >> $GITHUB_STEP_SUMMARY
            else
              CHANGED_FILES="${{ steps.changed-files-koin.outputs.all_changed_files }}"
              COUNT=$(echo "$CHANGED_FILES" | wc -w)
              echo "Detected $COUNT file changes:" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "$CHANGED_FILES" | tr ' ' '\n' >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          # Koin-Annotations repository summary
          echo "### Koin-Annotations Repository" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            echo "First run - processed all documentation files" >> $GITHUB_STEP_SUMMARY
            FILES="${{ steps.all-files-annotations.outputs.all_changed_files }}"
            COUNT=$(echo "$FILES" | wc -w)
            echo "Processed $COUNT files in total" >> $GITHUB_STEP_SUMMARY
          else
            if [ -z "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]; then
              echo "No document changes detected" >> $GITHUB_STEP_SUMMARY
            else
              CHANGED_FILES="${{ steps.changed-files-annotations.outputs.all_changed_files }}"
              COUNT=$(echo "$CHANGED_FILES" | wc -w)
              echo "Detected $COUNT file changes:" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "$CHANGED_FILES" | tr ' ' '\n' >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          fi