name: Koin docs update

on:
#  schedule:
#    - cron: '0 0 * * 0'  # 每周日 UTC 时间 0:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  check-external-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以进行差异比较

      - name: Checkout Koin repository
        uses: actions/checkout@v4
        with:
          repository: InsertKoinIO/koin
          path: koin-repo

      - name: Checkout Koin Annotations repository
        uses: actions/checkout@v4
        with:
          repository: InsertKoinIO/koin-annotations
          path: koin-annotations-repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @google/genai

      - name: Check last run timestamp for Koin
        id: last-run-koin
        run: |
          if [ -f ".github/last_check_koin.txt" ]; then
            echo "first_run=false" >> $GITHUB_OUTPUT
            echo "last_commit=$(cat .github/last_check_koin.txt)" >> $GITHUB_OUTPUT
          else
            echo "first_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Check last run timestamp for Koin-Annotations
        id: last-run-annotations
        run: |
          if [ -f ".github/last_check_koin_annotations.txt" ]; then
            echo "first_run=false" >> $GITHUB_OUTPUT
            echo "last_commit=$(cat .github/last_check_koin_annotations.txt)" >> $GITHUB_OUTPUT
          else
            echo "first_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Get current commit for Koin
        id: current-commit-koin
        run: |
          cd koin-repo
          echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get current commit for Koin-Annotations
        id: current-commit-annotations
        run: |
          cd koin-annotations-repo
          echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check if commits have changed
        id: check-commits
        run: |
          # 检查 Koin 仓库的 commit 是否变化
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            echo "koin_changed=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.last-run-koin.outputs.last_commit }}" != "${{ steps.current-commit-koin.outputs.current_commit }}" ]; then
            echo "koin_changed=true" >> $GITHUB_OUTPUT
          else
            echo "koin_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # 检查 Koin-Annotations 仓库的 commit 是否变化
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            echo "annotations_changed=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.last-run-annotations.outputs.last_commit }}" != "${{ steps.current-commit-annotations.outputs.current_commit }}" ]; then
            echo "annotations_changed=true" >> $GITHUB_OUTPUT
          else
            echo "annotations_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # 任一仓库有变化
          if [[ "${{ steps.check-commits.outputs.koin_changed }}" == "true" || "${{ steps.check-commits.outputs.annotations_changed }}" == "true" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi
          
          echo "Koin 仓库变化: ${{ steps.check-commits.outputs.koin_changed }}"
          echo "Koin-Annotations 仓库变化: ${{ steps.check-commits.outputs.annotations_changed }}"
          echo "任一仓库变化: ${{ steps.check-commits.outputs.any_changed }}"

      - name: Get changed markdown files for Koin
        id: changed-files-koin
        if: steps.check-commits.outputs.koin_changed == 'true'
        uses: tj-actions/changed-files@v46.0.3
        with:
          path: koin-repo
          base_sha: ${{ steps.last-run-koin.outputs.last_commit }}
          files: |
            docs/**/*.md

      - name: Get changed markdown files for Koin-Annotations
        id: changed-files-annotations
        if: steps.check-commits.outputs.annotations_changed == 'true'
        uses: tj-actions/changed-files@v46.0.3
        with:
          path: koin-annotations-repo
          base_sha: ${{ steps.last-run-annotations.outputs.last_commit }}
          files: |
            docs/**/*.md

      - name: Get all markdown files for Koin (first run)
        id: all-files-koin
        if: steps.last-run-koin.outputs.first_run == 'true'
        run: |
          cd koin-repo
          ALL_FILES=$(find docs -name "*.md" | tr '\n' ' ' | sed 's/ $//')
          echo "all_changed_files=$ALL_FILES" >>  $GITHUB_OUTPUT

      - name: Get all markdown files for Koin-Annotations (first run)
        id: all-files-annotations
        if: steps.last-run-annotations.outputs.first_run == 'true'
        run: |
          cd koin-annotations-repo
          ALL_FILES=$(find docs -name "*.md" | tr '\n' ' ' | sed 's/ $//')
          echo "all_changed_files=$ALL_FILES" >>  $GITHUB_OUTPUT

      - name: Prepare files for translation
        id: prepare-translation
        run: |
          # 处理 Koin 仓库文件
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            # 首次运行 - 使用所有文件
            echo "KOIN_CHANGED_FILES=${{ steps.all-files-koin.outputs.all_changed_files }}" >> $GITHUB_ENV
            echo "koin_any_changed=true" >> $GITHUB_OUTPUT
          else
            # 后续运行 - 使用变更的文件
            echo "KOIN_CHANGED_FILES=${{ steps.changed-files-koin.outputs.all_changed_files }}" >> $GITHUB_ENV
          
            if [ -n "${{ steps.changed-files-koin.outputs.all_changed_files }}" ]; then
              echo "koin_any_changed=true" >> $GITHUB_OUTPUT
            else
              echo "koin_any_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          # 处理 Koin-Annotations 仓库文件
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            # 首次运行 - 使用所有文件
            echo "ANNOTATIONS_CHANGED_FILES=${{ steps.all-files-annotations.outputs.all_changed_files }}" >> $GITHUB_ENV
            echo "annotations_any_changed=true" >> $GITHUB_OUTPUT
          else
            # 后续运行 - 使用变更的文件
            echo "ANNOTATIONS_CHANGED_FILES=${{ steps.changed-files-annotations.outputs.all_changed_files }}" >> $GITHUB_ENV
          
            if [ -n "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]; then
              echo "annotations_any_changed=true" >> $GITHUB_OUTPUT
            else
              echo "annotations_any_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          # 任一仓库有变更
          if [[ "${{ steps.last-run-koin.outputs.first_run }}" == "true" || "${{ steps.last-run-annotations.outputs.first_run }}" == "true" || -n "${{ steps.changed-files-koin.outputs.all_changed_files }}" || -n "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # 保存当前提交的SHA以便后续更新
          cd koin-repo
          echo "KOIN_CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
          cd ../koin-annotations-repo
          echo "ANNOTATIONS_CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Translate Koin docs
        if: steps.prepare-translation.outputs.koin_any_changed == 'true'
        env:
          BASE_DIR: ./koin
          START_PAGE: koin.md
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CHANGED_FILES: ${{ env.KOIN_CHANGED_FILES }}
          REPO_PATH: koin-repo
        run: node .github/workflows/translate.js

      - name: Translate Koin-Annotations docs
        if: steps.prepare-translation.outputs.annotations_any_changed == 'true'
        env:
          BASE_DIR: ./koin
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CHANGED_FILES: ${{ env.ANNOTATIONS_CHANGED_FILES }}
          REPO_PATH: koin-annotations-repo
        run: node .github/workflows/translate.js

      - name: Update last check timestamps
        if: success() && steps.prepare-translation.outputs.any_changed == 'true'
        run: |
          # 只有在前面所有步骤都成功时才更新最后检查的提交
          echo "${{ env.KOIN_CURRENT_COMMIT }}" > .github/last_check_koin.txt
          echo "${{ env.ANNOTATIONS_CURRENT_COMMIT }}" > .github/last_check_koin_annotations.txt
          echo "已更新检查记录时间戳"

      - name: Commit and push changes
        if: steps.prepare-translation.outputs.any_changed == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          # 排除不需要提交的文件和目录
          git add . ':!package.json' ':!package-lock.json' ':!koin-repo' ':!koin-repo/**' ':!koin-annotations-repo' ':!koin-annotations-repo/**'
          git commit -m '添加翻译文件并更新检查记录'
          git push origin main

      - name: Create summary
        if: always()
        run: |
          echo "## 文档更新检测" >> $GITHUB_STEP_SUMMARY
          
          # 检查 commit 是否变化
          echo "### Commit 变化检测" >> $GITHUB_STEP_SUMMARY
          echo "- Koin 仓库: ${{ steps.check-commits.outputs.koin_changed }}" >> $GITHUB_STEP_SUMMARY
          echo "- Koin-Annotations 仓库: ${{ steps.check-commits.outputs.annotations_changed }}" >> $GITHUB_STEP_SUMMARY
          
          # Koin 仓库摘要
          echo "### Koin 仓库" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.last-run-koin.outputs.first_run }}" == "true" ]; then
            echo "首次运行 - 已处理所有文档文件" >> $GITHUB_STEP_SUMMARY
            FILES="${{ steps.all-files-koin.outputs.all_changed_files }}"
            COUNT=$(echo "$FILES" | wc -w)
            echo "共处理 $COUNT 个文件" >> $GITHUB_STEP_SUMMARY
          else
            if [ -z "${{ steps.changed-files-koin.outputs.all_changed_files }}" ]; then
              echo "没有检测到文档变更" >> $GITHUB_STEP_SUMMARY
            else
              CHANGED_FILES="${{ steps.changed-files-koin.outputs.all_changed_files }}"
              COUNT=$(echo "$CHANGED_FILES" | wc -w)
              echo "检测到 $COUNT 个文件变更:" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "$CHANGED_FILES" | tr ' ' '\n' >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          # Koin-Annotations 仓库摘要
          echo "### Koin-Annotations 仓库" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.last-run-annotations.outputs.first_run }}" == "true" ]; then
            echo "首次运行 - 已处理所有文档文件" >> $GITHUB_STEP_SUMMARY
            FILES="${{ steps.all-files-annotations.outputs.all_changed_files }}"
            COUNT=$(echo "$FILES" | wc -w)
            echo "共处理 $COUNT 个文件" >> $GITHUB_STEP_SUMMARY
          else
            if [ -z "${{ steps.changed-files-annotations.outputs.all_changed_files }}" ]; then
              echo "没有检测到文档变更" >> $GITHUB_STEP_SUMMARY
            else
              CHANGED_FILES="${{ steps.changed-files-annotations.outputs.all_changed_files }}"
              COUNT=$(echo "$CHANGED_FILES" | wc -w)
              echo "检测到 $COUNT 个文件变更:" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "$CHANGED_FILES" | tr ' ' '\n' >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          fi